### ISSUE TITLE
Compatibility with Node 0.6

### ISSUE THREAD

**Issue by gitfy** [rubenv/zipper#1]
Hi,
Can you pls update you package.json and make it compatible with the latest node 0.6. it will help us update our environment.

Thanks.

**Comment by rubenv** [comment]
Yes, this is planned. I made the version explicit to make sure it is tested. It might just work, but unless we test it, we won't know. Soon.

**Comment by xjamundx** [comment]
This would be sweet!

**Comment by rubenv** [comment]
Should work on Node 0.6.x now, enjoy!

**Comment by gitfy** [comment]
Thanks.
