### ISSUE TITLE
Erro ao instalar o Zipper

### ISSUE THREAD

**Issue by SouzaRob** [rubenv/zipper#13]
Boa tarde comunidade,
alguem ja recebeu o erro abaixo ao tentar o zipper? Estou parado nesse erro e por isso não consigo seguir com o curso.

Obrigado pela atenção de todos.

Att,
Robnei Souza

![erro1](https://cloud.githubusercontent.com/assets/27024673/24882055/20f765ec-1e16-11e7-8360-54d7276869dc.jpg)
![erro2](https://cloud.githubusercontent.com/assets/27024673/24882292/f203a48e-1e16-11e7-9da7-34d66dcd7a4b.jpg)

![versao node-npm](https://cloud.githubusercontent.com/assets/27024673/24882056/20f8e944-1e16-11e7-92cd-1ddff26a1e81.jpg)

**Comment by rubenv** [comment]
I'm sorry, I don't speak Portuguese. Error pretty much tells you exactly what is wrong: you have no write permissions in your `node_modules` folder.

**Comment by SouzaRob** [comment]
thanks, problem solved.
