### ISSUE TITLE
Install failed with NPM

### ISSUE THREAD

**Issue by futur** [rubenv/zipper#5]
Hi,
I got the following error installing zipper in my machine,

Mac osx lion 10.7.2
Node version - v0.6.13
# 

Build failed:
 -> task failed (err #1): 
    {task: cxx _zipper.cc -> _zipper_1.o}
 -> task failed (err #1): 
    {task: cxx zipper.cpp -> zipper_1.o}

npm ERR! zipper@0.1.1 install: `node-waf configure build`
npm ERR! `sh "-c" "node-waf configure build"` failed with 1
npm ERR! 
npm ERR! Failed at the zipper@0.1.1 install script.
npm ERR! This is most likely a problem with the zipper package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-waf configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls zipper
npm ERR! There is likely additional logging output above.
npm ERR! 
npm ERR! System Darwin 11.2.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "zipper"
npm ERR! cwd /Users/user/Projects/sample
npm ERR! node -v v0.6.13
npm ERR! npm -v 1.1.9
npm ERR! code ELIFECYCLE
npm ERR! message zipper@0.1.1 install: `node-waf configure build`
npm ERR! message `sh "-c" "node-waf configure build"` failed with 1
npm ERR! errno {}
npm ERR! '

---

**Comment by gitfy** [comment]
For me as well.

Here is the detailed info :

make: **\* No targets specified and no makefile found.  Stop.
[1/3] cxx: src/_zipper.cc -> build/Release/src/_zipper_1.o
[2/3] cxx: src/zipper.cpp -> build/Release/src/zipper_1.o
In file included from ../src/zipper.cpp:1In file included from ../src/_zipper.cc:9:
../src/zipper.hpp:15:17::
 ../src/zipper.hpp:15:17:error:  zip.h: No such file or directory
error: zip.h: No such file or directory
../src/zipper.cpp: In destructor ‘virtual Zipper::~Zipper()’:
../src/zipper.cpp:38: error: ‘zip_close’ was not declared in this scope
../src/zipper.cpp: In static member function ‘static v8::Handlev8::Value Zipper::New(const v8::Arguments&)’:
../src/zipper.cpp:56: error: ‘ZIP_CREATE’ was not declared in this scope
../src/zipper.cpp:56: error: ‘zip_open’ was not declared in this scope
../src/zipper.cpp:57: error: ‘zip_error_to_str’ was not declared in this scope
../src/zipper.cpp: In static member function ‘static v8::Handlev8::Value Zipper::addFile(const v8::Arguments&)’:
../src/zipper.cpp:119: error: ‘ZIP_CREATE’ was not declared in this scope
../src/zipper.cpp:119: error: ‘zip_open’ was not declared in this scope
../src/zipper.cpp:120: error: ‘zip_error_to_str’ was not declared in this scope
../src/zipper.cpp:123: error: ‘zip_close’ was not declared in this scope
../src/zipper.cpp: In static member function ‘static void Zipper::EIO_AddFile(eio_req*)’:
../src/zipper.cpp:144: error: ‘zip_source_file’ was not declared in this scope
../src/zipper.cpp:145: error: ‘zip_add’ was not declared in this scope
../src/zipper.cpp:150: error: ‘zip_source_free’ was not declared in this scope
../src/zipper.cpp:153: error: ‘zip_close’ was not declared in this scope
../src/zipper.cpp:155: error: ‘zip_strerror’ was not declared in this scope
Waf: Leaving directory `/Users/lsubramanian/workspace2/ecl-ws/Avalon/node_modules/zipper/build'
Build failed:
 -> task failed (err #1): 
    {task: cxx _zipper.cc -> _zipper_1.o}
 -> task failed (err #1): 
    {task: cxx zipper.cpp -> zipper_1.o}

**Comment by kahlow** [comment]
I'm having the same issue :(

**Comment by rubenv** [comment]
@kahlow Is this also on 10.7 for you?

It installs just fine on my Mountain Lion machine. Unfortunately I do not have access to a Lion machine anymore.

**Comment by kahlow** [comment]
@rubenv this is on a Windows 7 pc (don't judge, it's a work machine haha).

Node: v0.8.21
NPM: 1.2.11

Error:
npm ERR! zipper@0.1.2 install: `node-waf configure build`
npm ERR! `cmd "/c" "node-waf configure build"` failed with 1
npm ERR!
npm ERR! Failed at the zipper@0.1.2 install script.
npm ERR! This is most likely a problem with the zipper package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-waf configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls zipper
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\Program Files (x86)\nodejs\\node.exe" "C:\Program Files (x86)\nodejs\node_modules\npm\bin\npm-cli.js" "install" "zipper"
npm ERR! cwd C:\Dev
npm ERR! node -v v0.8.19
npm ERR! npm -v 1.2.10
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Dev\npm-debug.log
npm ERR! not ok code 0

**Comment by rubenv** [comment]
@kahlow That's another issue then. The build should be converted to node-gyp to work on Windows, but I have no experience with that.

Original issue happens on OSX.

**Comment by rubenv** [comment]
I've changed the way this module is installed, should not happen anymore now. Please check.
