### ISSUE TITLE
CRC32 Error

### ISSUE THREAD

**Issue by basert** [rubenv/zipper#9]
node: symbol lookup error: /node_modules/zipper/build/Release/zipper.node: undefined symbol: crc32

Even on this simple code, the error occurs:

```
zipper = require('zipper').Zipper;
var zipfile = new zipper('zipfile.zip');
zipfile.addFile('myfile.txt', 'myfile.txt', function (err) {
});
```

System is nodejs 0.10.5 and ubuntu 12.04 tls

But this is working:

```
~$ crc32 ziptest.js
3b065cbb
```

**Comment by rubenv** [comment]
I've seen this on the Travis machines as well (which also use Ubuntu). I'll get a VM set up to figure this out.

**Comment by rubenv** [comment]
I've release `0.3.0`, which should fix this. Be sure to install `libzip-dev` first.

Let me know if things work now!
